= Reference

[#semver]
== `semver`

The `semver` template class implements the SemVer standard
footnote:semver[] as a composite of the <<version_core>>,
<<prerelease_version>>, and <<build_metadata>> components.
The implementation provides for conversion to and from strings, comparisons,
and hashing. Which makes it possible to use them as values in containers,
and keys in maps. The type of the version component is configurable to
customize for size.

[#semver-syn]
=== Class `semver` synopsis

[source]
----
include::../include/versioned/versioned.hpp[tag=semver-syn]
----

[#semver-types-vars]
=== Class `semver` types & variables

`version_t` <= `version_core< _Number_, 3 >`::
The type of the core version component. Default is `version_core<int,3>`.

`prerelease_t` <= `_Prerelease_`::
The type of the prerelease component. Default is `prerelease_version<int>.

`build_t` <= `_Build_`::
The type of the build tag component. Default is `build_metadata`.

[#semver-method]
=== Class `semver` functions

[#semver-method-version]
==== Function `semver::version`

[source]
----
const version_t & version() const;
version_t & version();
----

Returns a reference to the version component of the sematic version.

[#semver-method-prerelease]
==== Function `semver::prerelease`

[source]
----
const prerelease_t & prerelease() const;
prerelease_t & prerelease();
----

Returns a reference to the prerelease component of the semantic version.

[#semver-func-build]
==== Function `semver::build`

[source]
----
const build_t & build() const;
build_t & build();
----

Returns a reference to the build metadata component of the semantic version.

[#semver-func-major]
==== Function `semver::major`

[source]
----
typename version_t::element_t major() const;
----

Returns element `0` of the version component.

[#semver-func-minor]
==== Function `semver::minor`

[source]
----
typename version_t::element_t minor() const;
----

Returns element `1` of the version component.

[#semver-func-patch]
==== Function `semver::patch`

[source]
----
typename version_t::element_t patch() const;
----

Returns element `2` of the version component.

[#semver-func]
=== Class `semver` non-member functions

[#semver-func-from_chars]
==== Function `from_chars`

[source]
----
template <class N, class P, class B>
from_chars_result from_chars(
	const char * first, const char * last, semver<N, P, B> & value)
----

Parses the given string as a core version setting `value` to the version. If
parsing fails for any reason the `value` is unchanged.

Parameters::
	*first, last* - range of characters to parse;
	*value* - where the parsed value is stored.

Return::
	Returns a value of type `from_chars_result` that is compatible with
	the {CPP}17 `std::from_chars_result` type
	footnote:from_chars_result[`std::from_chars_result` (https://cppreference.com/w/cpp/utility/from_chars_result.html)].

[#semver-func-to_string]
==== Function `to_string`

[source]
----
template <class N, class P, class B>
::std::string to_string(const semver<N, P, B> & value)
----

Returns the formatted string representation following the SemVer footnote:semver[]
syntax.

Parameters::
	*value* - the `semver` to format.

Return::
	The SemVer footnote:semver[] string representation of the *value*.

Example::
+
[source]
----
include::example_semver_to_string.cpp[tag=example-code]
----
+
Output:
+
....
include::example_semver_to_string.out.txt[]
....

[#semver-func-compare]
==== Function `compare`

[source]
----
template <class N0, class P0, class B0, class N1, class P1, class B1>
int compare(const semver<N0, P0, B0> & a, const semver<N1, P1, B1> & b)
----

[#semver-func-equal]
==== Function `operator==`

[source]
----
template <class N0, class P0, class B0, class N1, class P1, class B1>
bool operator==(const semver<N0, P0, B0> & a, const semver<N1, P1, B1> & b)
----

[#semver-func-less]
==== Function `operator<`

[source]
----
template <class N0, class P0, class B0, class N1, class P1, class B1>
bool operator<(const semver<N0, P0, B0> & a, const semver<N1, P1, B1> & b)
----

[#semver-func-hash]
==== Function `hash`

[source]
----
template <class N, class P, class B>
::std::size_t hash(const semver<N, P, B> & value)
----

[#semver-func-get]
==== Function `get`

[source]
----
template <::std::size_t I, class N, class P, class B>
const typename ::std::tuple_element<I, semver<N, P, B>>::type &
	get(const semver<N, P, B> & value)
----

[#semver-helpers]
=== Class `semver` helpers

[#semver-std-hash]
==== Class `std::hash`

[source]
----
template <class N, class P, class B>
struct hash<::versioned::semver<N, P, B>>
----

[#version_core]
== `version_core`

[#version_core-syn]
=== Class `version_core` synopsis

[source]
----
include::../include/versioned/versioned.hpp[tag=version_core-sym]
----

[#version_core-types-vars]
=== Class `version_core` types & variables

`element_t` <= `_Number_`::
The type of the components of the version. This is a numeric type.

`element_c` <= `_Count_`::
The number of components of the version. Default is `3`.

[#version_core-method]
=== Class `version_core` functions

[#version_core-method-ctor]
==== Function `version_core::version_core`

[source]
----
template <class... I>
explicit version_core(element_t a0, I... an);
----

[#version_core-method-at]
==== Function `version_core::at`

[source]
----
element_t & at(::std::size_t i);
const element_t & at(::std::size_t i) const;
----

[#version_core-func]
=== Class `version_core` non-member functions

[#version_core-func-from_chars]
==== Function `from_chars`

[source]
----
template <class N, ::std::size_t C>
from_chars_result from_chars(
	const char * first, const char * last, version_core<N, C> & value)
----

[#version_core-func-to_string]
==== Function `to_string`

[source]
----
template <class N, ::std::size_t C>
::std::string to_string(const version_core<N, C> & value)
----

[#version_core-func-compare]
==== Function `compare`

[source]
----
template <class N0, ::std::size_t C0, class N1, ::std::size_t C1>
int compare(const version_core<N0, C0> & a, const version_core<N1, C1> & b)
----

[#version_core-func-equal]
==== Function `operator==`

[source]
----
template <class N0, ::std::size_t C0, class N1, ::std::size_t C1>
bool operator==(const version_core<N0, C0> & a, const version_core<N1, C1> & b)
----

[#version_core-func-less]
==== Function `operator<`

[source]
----
template <class N0, ::std::size_t C0, class N1, ::std::size_t C1>
bool operator<(const version_core<N0, C0> & a, const version_core<N1, C1> & b)
----

[#version_core-func-hash]
==== Function `hash`

[source]
----
template <class N, ::std::size_t C>
::std::size_t hash(const version_core<N, C> & value)
----

[#version_core-func-get]
==== Function `get`

[source]
----
template <size_t I, class N, ::std::size_t C>
const typename version_core<N, C>::element_t & get(
	const version_core<N, C> & value)
----

[#version_core-helpers]
=== Class `version_core` helpers

[#version_core-helpers-hash]
==== Class `std::hash<::versioned::version_core>`

[source]
----
namespace std {
template <class N, ::std::size_t C>
struct hash<::versioned::version_core<N, C>>
}
----

[#version_core-helpers-tuple_size]
==== Class `std::tuple_size<::versioned::version_core>`

[source]
----
namespace std {
template <class N, ::std::size_t C>
struct tuple_size<::versioned::version_core<N, C>>
	: integral_constant<::std::size_t,
		  ::versioned::version_core<N, C>::element_c>
}
----

[#version_core-helpers-tuple_element]
==== Class `std::tuple_element<size_t, ::versioned::version_core>`

[source]
----
namespace std {
template <size_t I, class N, ::std::size_t C>
struct tuple_element<I, ::versioned::version_core<N, C>>
}
----

[#version_tag]
== `version_tag`

[#version_tag-syn]
=== Class `version_tag` synopsis

[source]
----
include::../include/versioned/versioned.hpp[tag=version_tag-syn]
----

[#version_tag-types-vars]
=== Class `version_tag` types & variables


`element_t` <= `::std::string`::
The type of the tag value.

`range_element_t` <= `::std::tuple<const char *, const char *>`::
The type for subranges of the components of the tag.

[#version_tag-method]
=== Class `version_tag` functions

[#version_tag-method-ctor]
==== Function `version_tag::version_tag`

[source]
----
template <class... S>
explicit version_tag(const char * a0, S... an);
template <class... S>
explicit version_tag(const ::std::string & a0, S... an);
----

[#version_tag-method-at]
==== Function `version_tag::at`

[source]
----
element_t at(::std::size_t i) const;
----

[#version_tag-method-range_at]
==== Function `version_tag::range_at`

[source]
----
range_element_t range_at(::std::size_t i) const;
----

[#version_tag-method-empty]
==== Function `version_tag::empty`

[source]
----
bool empty() const;
----

[#version_tag-method-size]
==== Function `version_tag::size`

[source]
----
::std::size_t size() const;
----

[#version_tag-func]
=== Class `version_tag` non-member functions

[#version_tag-func-from_chars]
==== Function `from_chars`

[source]
----
inline from_chars_result from_chars(
	const char * first, const char * last, version_tag & value)
----

[#version_tag-func-to_string]
==== Function `to_string`

[source]
----
inline ::std::string to_string(const version_tag & value)
----

[#version_tag-func-compare]
==== Function `compare`

[source]
----
inline int compare(const version_tag & a, const version_tag & b)
----

[#version_tag-func-equal]
==== Function `operator==`

[source]
----
inline bool operator==(const version_tag & a, const version_tag & b)
----

[#version_tag-func-less]
==== Function `operator<`

[source]
----
inline bool operator<(const version_tag & a, const version_tag & b)
----

[#version_tag-func-hash]
==== Function `hash`

[source]
----
inline ::std::size_t hash(const version_tag & value)
----

[#version_tag-helpers]
=== Class `version_tag` helpers

[#version_tag-helpers-hash]
==== Class `std::hash<::versioned::version_tag>`

[source]
----
namespace std {
template <>
struct hash<::versioned::version_tag>
}
----

[#prerelease_version]
== `prerelease_version`

[#prerelease_version-syn]
=== Class `prerelease_version` synopsis

[source]
----
include::../include/versioned/versioned.hpp[tag=prerelease_version-syn]
----

[#prerelease_version-types-vars]
=== Class `prerelease_version` types & variables


`number_element_t` <= `_Number_`::
The type of the pre-release version component, if a component is numeric.

[#prerelease_version-method]
=== Class `prerelease_version` functions

[#prerelease_version-method-number_at]
==== Function `prerelease_version::number_at`

[source]
----
number_element_t number_at(::std::size_t i) const;
----

[#prerelease_version-method-is_number_at]
==== Function `prerelease_version::is_number_at`
----
bool is_number_at(::std::size_t i) const;
----

[#prerelease_version-func]
=== Class `prerelease_version` non-member functions

[#prerelease_version-func-compare]
==== Function `compare`
----
template <class N0, class N1>
int compare(const prerelease_version<N0> & a, const prerelease_version<N1> & b)
----

[#prerelease_version-func-equal]
==== Function `operator==`
----
template <class N0, class N1>
bool operator==(
	const prerelease_version<N0> & a, const prerelease_version<N1> & b)
----

[#prerelease_version-func-less]
==== Function `operator<`
----
template <class N0, class N1>
bool operator<(
	const prerelease_version<N0> & a, const prerelease_version<N1> & b)
----

[#prerelease_version-func-hash]
==== Function `hash`
----
template <class N>
::std::size_t hash(const prerelease_version<N> & value)
----

[#prerelease_version-helpers]
=== Class `prerelease_version` helpers

[#prerelease_version-helpers-hash]
==== Class `std::hash<::versioned::prerelease_version>`

[source]
----
std {
template <class N>
struct hash<::versioned::prerelease_version<N>>
}
----

[#build_metadata]
== `build_metadata`

[#build_metadata-syn]
=== Class `build_metadata` synopsis

[source]
----
include::../include/versioned/versioned.hpp[tag=build_metadata-syn]
----
