name: Rust

on:
  push:
    branches: ["main"]
    paths: [".github/workflows/rust*.yml", "rust/**"]
  pull_request:
    branches: ["main"]
    paths: [".github/workflows/rust*.yml", "rust/**"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: ["macos-latest", "ubuntu-latest"]
        rust-version: ["default"]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.rust-version }}/${{ matrix.os }}
    steps:
      - uses: actions/checkout@master

      - name: Info
        run: |
          cargo --version -v
          rustc --version -v

      - name: Build
        run: |
          cd rust
          cargo build --verbose

      - name: Test
        run: |
          cd rust
          cargo test --verbose
