name: Rust

on:
  push:
    branches: ["main"]
    paths: [".github/workflows/rust*.yml", "rust/**"]
  pull_request:
    branches: ["main"]
    paths: [".github/workflows/rust*.yml", "rust/**"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: ["macos-latest", "ubuntu-latest"]
        rust-version: ["stable"]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.rust-version }}/${{ matrix.os }}
    steps:
      - name: Install/POSIX
        if: ${{ startsWith( matrix.os, 'ubuntu' ) || startsWith( matrix.os, 'macos' ) }}
        shell: bash
        run: |
          cd $HOME
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          ls -laF

      - uses: actions/checkout@master

      - name: Info
        run: |
          which rustup
          which cargo
          cargo --version -v
          which rustc
          rustc --version -v

      - name: Build
        run: |
          cd rust
          cargo build --verbose

      - name: Test
        run: |
          cd rust
          cargo test --verbose
