name: Swift

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  SWIFTLY_INIT: init --skip-install --verbose --assume-yes
  SWIFTLY_INSTALL: install --use --verbose --assume-yes --post-install-file=post-install.sh
  SWIFTLY_DL: https://download.swift.org/swiftly
  SWIFTLY_HOME_DIR: $GITHUB_WORKSPACE/../_swiftly
  SWIFTLY_BIN_DIR: $GITHUB_WORKSPACE/../_swiftly/bin

jobs:
  build:
    strategy:
      matrix:
        os: ["macos-latest", "ubuntu-latest"]
        swift-version: ["6.1", "6.0"]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.swift-version }}/${{ matrix.os }}
    steps:
      - name: Install/macOS
        if: ${{ startsWith( matrix.os, 'macos' ) }}
        shell: bash
        run: |
          mkdir $SWIFTLY_HOME_DIR
          cd $SWIFTLY_HOME_DIR
          curl -O $SWIFTLY_DL/darwin/swiftly.pkg
          installer -pkg swiftly.pkg -target CurrentUserHomeDirectory

      - name: Install/Linux
        if: ${{ startsWith( matrix.os, 'ubuntu' ) }}
        shell: bash
        run: |
          sudo apt-get -y install libcurl4-openssl-dev
          mkdir $SWIFTLY_HOME_DIR
          cd $SWIFTLY_HOME_DIR
          curl -O $SWIFTLY_DL/linux/swiftly-$(uname -m).tar.gz
          tar vzxf swiftly-$(uname -m).tar.gz

      - name: Install/Post
        if: ${{ startsWith( matrix.os, 'ubuntu' ) || startsWith( matrix.os, 'macos' ) }}
        shell: bash
        run: |
          cd $SWIFTLY_HOME_DIR
          $SWIFTLY_HOME_DIR/swiftly $SWIFTLY_INIT
          $SWIFTLY_HOME_DIR/swiftly $SWIFTLY_INSTALL ${{ matrix.swift-version }}
          if [ -f $SWIFTLY_HOME_DIR/post-install.sh ]; then
            . $SWIFTLY_HOME_DIR/post-install.sh
          fi

      - uses: actions/checkout@master

      - name: Info
        shell: bash
        run: |
          . $SWIFTLY_HOME_DIR/env.sh && hash -r
          cd swift
          swift --version -v

      - name: Build
        shell: bash
        run: |
          . $SWIFTLY_HOME_DIR/env.sh && hash -r
          cd swift
          swift build -v

      - name: Test
        shell: bash
        run: |
          . $SWIFTLY_HOME_DIR/env.sh && hash -r
          cd swift
          swift test -v
