name: Swift

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  SWIFTLY_INIT: init --skip-install --verbose --assume-yes
  SWIFTLY_INSTALL: install --use --verbose --assume-yes --post-install-file=post-install.sh
  SWIFTLY_DL: https://download.swift.org/swiftly

jobs:
  build:
    strategy:
      matrix:
        os: ["macos-latest", "ubuntu-latest"]
        swift-version: ["6.1", "6.0"]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.swift-version }}/${{ matrix.os }}
    steps:
      - name: Install/Pre/macOS
        if: ${{ startsWith( matrix.os, 'macos' ) }}
        shell: bash
        run: |
          mkdir -p $HOME/.swiftly/install
          cd $HOME/.swiftly/install
          curl -O $SWIFTLY_DL/darwin/swiftly.pkg
          installer -pkg swiftly.pkg -target CurrentUserHomeDirectory
          ln $HOME/.swiftly/bin/swiftly swiftly

      - name: Install/Pre/Linux
        if: ${{ startsWith( matrix.os, 'ubuntu' ) }}
        shell: bash
        run: |
          sudo apt-get -y install libcurl4-openssl-dev
          mkdir -p $HOME/.swiftly/install
          cd $HOME/.swiftly/install
          curl -O $SWIFTLY_DL/linux/swiftly-$(uname -m).tar.gz
          tar vzxf swiftly-$(uname -m).tar.gz

      - name: Install/Post/POSIX
        if: ${{ startsWith( matrix.os, 'ubuntu' ) || startsWith( matrix.os, 'macos' ) }}
        shell: bash
        run: |
          cd $HOME/.swiftly
          ls -laF ./install
          export SWIFTLY_HOME_DIR=$HOME/.swiftly
          ./install/swiftly $SWIFTLY_INIT
          ./bin/swiftly $SWIFTLY_INSTALL ${{ matrix.swift-version }}
          if [ -f ./post-install.sh ]; then
            . ./post-install.sh
          fi

      - uses: actions/checkout@master

      - name: Info
        shell: bash
        run: |
          $HOME/.swiftly/bin/swiftly use ${{ matrix.swift-version }}
          hash -r
          cd swift
          swift --version -v

      - name: Build
        shell: bash
        run: |
          $HOME/.swiftly/bin/swiftly use ${{ matrix.swift-version }}
          hash -r
          cd swift
          swift build -v

      - name: Test
        shell: bash
        run: |
          $HOME/.swiftly/bin/swiftly use ${{ matrix.swift-version }}
          hash -r
          cd swift
          swift test -v
