name: Swift

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    strategy:
      matrix:
        os: ["macos-latest", "ubuntu-latest", "windows-latest"]
        swift-version: ["6.1", "6.0"]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.swift-version }}/${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
      - name: Install
        uses: sushichop/gha-swift-env@V1
        with:
          swift-version: ${{ matrix.swift-version }}
      - name: Info
        run: |
          cd swift
          swift --version -v
      - name: Build
        run: |
          cd swift
          swift build -v
      - name: Test
        run: |
          cd swift
          swift test -v
