name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@master
    - name: Build
      run: |
        cd swift
        swift build -v
    - name: Run tests
      run: |
        cd swift
        swift test -v
